version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: user-management-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: usermanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: